import { Geist, Geist_Mono,Inter, Raleway,Carlito } from "next/font/google";

import "./globals.css";
import BackGround from "@/components/Background/BackGround";
import  UserProvider  from "../context/userProvider"
import { Toaster } from "@/components/ui/sonner"

const inter=Inter({
  variable:"--font-inter",
  subsets:["latin"]
});

const raleway=Raleway({
  variable:"--font-Raleway",
  subsets:["latin"]
})

const carlito=Carlito({
  variable:"--font-Carlito",
  subsets:["latin"],
  weight: ["400", "700"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${inter.variable} ${geistMono.variable} ${raleway.variable} ${carlito.variable} antialiased `} suppressHydrationWarning
      >
       
    
      
    <UserProvider>
        <BackGround>  
                       {children}
                          <Toaster className="relative z-50" />
                       
        </BackGround>
       

    </UserProvider>
    
      
    </body>
    </html>
  );
}
